import 'dart:convert';

import 'package:built_collection/built_collection.dart';
import 'package:http/http.dart' as http;
import 'package:lib_management/models/location.dart';

class DataServices {
  Future<BuiltList<Location>?> getlocations() async {
    final response =
        await http.get(Uri.parse('http://172.16.53.74:3000/viewbooks?page=1'));
    try {
      if (response.statusCode == 200) {
        List<dynamic> list = json.decode(response.body);
        final List<Location> l = <Location>[];
        for (final dynamic data in list) {
          final Map<String, dynamic> d = data as Map<String, dynamic>;
          l.add(Location.fromJson(d));
        }
        return l.toBuiltList();
      } else {
        print(response);
      }
    } catch (e) {
      List<dynamic> list = [
        {
          "SLNO": 1,
          "AUTHORS": "Venkataraman (M K)",
          "TITLE": "A Text Book of Statics",
          "EDITION": 8,
          "YEAR": 1995,
          "PUBLISHER": "Agasthiar Publication, Trichy",
          "SERIES": null,
          "PAGES": "420p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 55,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 2,
          "AUTHORS": "Singal (M K), Asha (Rani Singal)",
          "TITLE": "A First Course in Real Analysis",
          "EDITION": 18,
          "YEAR": 1985,
          "PUBLISHER": "R. Chand & Co., New Delhi",
          "SERIES": null,
          "PAGES": "408p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 70,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 3,
          "AUTHORS": "Mittal (P K)",
          "TITLE": "Introduction to Matrices",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Har Anand Publications",
          "SERIES": null,
          "PAGES": "159p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 4,
          "AUTHORS": "Shanthi (Narayan)",
          "TITLE": "Theory of Functions of a Complex Variable",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "371p",
          "PRICE_FOREIGN": " ",
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": "81-219-0639-3"
        },
        {
          "SLNO": 5,
          "AUTHORS": "Chorlton (Frank)",
          "TITLE": "Text Book of Fluid Dynamics",
          "EDITION": null,
          "YEAR": 1985,
          "PUBLISHER": "CBS Publishers & Distributors",
          "SERIES": null,
          "PAGES": "400p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 45,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 6,
          "AUTHORS": "Aggarwal (R S)",
          "TITLE": "A Text Book on Differential Equations & Dynamics",
          "EDITION": null,
          "YEAR": 1990,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "351p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 35,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 7,
          "AUTHORS": "Ray (M), Sharma (G C)",
          "TITLE": "A Text Book on Dynamics",
          "EDITION": 12,
          "YEAR": 1994,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "322p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 50,
          "P": "0.0",
          "ISBN": "81-219-0342-4"
        },
        {
          "SLNO": 8,
          "AUTHORS": "Sharma (J N)",
          "TITLE": "Functions of Complex Variable ",
          "EDITION": 20,
          "YEAR": 1995,
          "PUBLISHER": "Krishna Prakashan Mandir",
          "SERIES": null,
          "PAGES": "582p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 85,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 9,
          "AUTHORS": "Sharma (G S), Sharma (ER J J S)",
          "TITLE": "A Text book of engineering mathematics Vol -II",
          "EDITION": 3,
          "YEAR": 1992,
          "PUBLISHER": "CBS Publishers & Distributors",
          "SERIES": null,
          "PAGES": "90p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 10,
          "AUTHORS": "Sankara (Rao K)",
          "TITLE": "Introduction to Partial Differential Equations",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "357p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 175,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 11,
          "AUTHORS": "Patil (S H)",
          "TITLE": "Elements of Modern Physics",
          "EDITION": 4,
          "YEAR": 1992,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "402p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 78,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 12,
          "AUTHORS": "Kandasamy (P), Thilagavathy (K)",
          "TITLE": "Engineering Mathematics Vlume -II",
          "EDITION": 3,
          "YEAR": 1996,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "484p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 90,
          "P": "0.0",
          "ISBN": "81-219-0611-3"
        },
        {
          "SLNO": 13,
          "AUTHORS": "Kapur (J N)",
          "TITLE": "Mathematical Modelling",
          "EDITION": null,
          "YEAR": 1990,
          "PUBLISHER": "Wiley Eastern Ltd",
          "SERIES": null,
          "PAGES": "259p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 65,
          "P": "0.0",
          "ISBN": "81-224-0006-x"
        },
        {
          "SLNO": 14,
          "AUTHORS": "Sastry (S S)",
          "TITLE": "Engineering Mathematics Volume -I",
          "EDITION": 2,
          "YEAR": 1994,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "630p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 175,
          "P": "0.0",
          "ISBN": "81-203-0804-2"
        },
        {
          "SLNO": 15,
          "AUTHORS": "Jaggi (V P), Sushma (Jain)",
          "TITLE": "Computers for Everyone",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Academic Publisher",
          "SERIES": null,
          "PAGES": "169p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 30,
          "P": "0.0",
          "ISBN": "81-85185-16-6"
        },
        {
          "SLNO": 16,
          "AUTHORS": "Dev (Raj), Chatwal (R K)",
          "TITLE": "Mathematics Part-II",
          "EDITION": 3,
          "YEAR": 1992,
          "PUBLISHER": "CBS Publishers & Distributors",
          "SERIES": null,
          "PAGES": "530p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 70,
          "P": "0.0",
          "ISBN": "81-239-0010-4"
        },
        {
          "SLNO": 17,
          "AUTHORS": "Jaggi (V P), Sushma (Jain)",
          "TITLE": "Computers for Enginners",
          "EDITION": 16,
          "YEAR": 1995,
          "PUBLISHER": "Academic Publisher",
          "SERIES": null,
          "PAGES": "188p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 18,
          "AUTHORS": "Mahanli (P K), Mukherjee (I)",
          "TITLE": "Introduction to PC Softwares",
          "EDITION": 1,
          "YEAR": 1995,
          "PUBLISHER": "Academic Publisher",
          "SERIES": null,
          "PAGES": "167p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 45,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 19,
          "AUTHORS": "Sarda (N L)",
          "TITLE": "Programming in Pascal",
          "EDITION": 2,
          "YEAR": 1998,
          "PUBLISHER": "Pitambar Publishing Company",
          "SERIES": null,
          "PAGES": "322p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 40,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 20,
          "AUTHORS": "Jaggi (V P), Sushma (Jain)",
          "TITLE": "Basic for Beginners",
          "EDITION": 15,
          "YEAR": 1995,
          "PUBLISHER": "Preademic Publisher",
          "SERIES": null,
          "PAGES": "465p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 85,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 21,
          "AUTHORS": "Aggarwal (V B), Goel (M P)",
          "TITLE": "Work Book in Basic",
          "EDITION": 3,
          "YEAR": 1996,
          "PUBLISHER": "Pitambar Publishing Company",
          "SERIES": null,
          "PAGES": "178p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 50,
          "P": "0.0",
          "ISBN": "81-209-0017-0"
        },
        {
          "SLNO": 22,
          "AUTHORS": "Patodia (P L), Patodia (Manju)",
          "TITLE": "C Through Examples",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Academic Publisher",
          "SERIES": null,
          "PAGES": "159p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 50,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 23,
          "AUTHORS": "Khurmi (R S), Sedha (R S)",
          "TITLE": "Material Science",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "381p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 55,
          "P": "0.0",
          "ISBN": "81-219-0146-4"
        },
        {
          "SLNO": 24,
          "AUTHORS": "Sarda (N L)",
          "TITLE": "Structural Cobol Programming with Business Applications",
          "EDITION": 1,
          "YEAR": 1994,
          "PUBLISHER": "Pitambar Publishing Company",
          "SERIES": null,
          "PAGES": "332p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": "81-209-0016-2"
        },
        {
          "SLNO": 25,
          "AUTHORS": "Gupta (H C)",
          "TITLE": "Solid State Physics",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Vikas Publishing House",
          "SERIES": null,
          "PAGES": "406p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 85,
          "P": "0.0",
          "ISBN": "0-7069-9004-8"
        },
        {
          "SLNO": 26,
          "AUTHORS": "Prakash (Satya)",
          "TITLE": "Modern Physics",
          "EDITION": 8,
          "YEAR": 1994,
          "PUBLISHER": "Ratan Prakashan Mandir",
          "SERIES": null,
          "PAGES": "275p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 45,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 27,
          "AUTHORS": "Agrawal (J P), Agrawal (Amit)",
          "TITLE": "Solid State Electronics",
          "EDITION": 1,
          "YEAR": 1995,
          "PUBLISHER": "Pragati Prakashan",
          "SERIES": null,
          "PAGES": "309p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 55,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 28,
          "AUTHORS": "Venkataraman (G)",
          "TITLE": "Chandrasekhar and his Limit",
          "EDITION": 1,
          "YEAR": 1993,
          "PUBLISHER": "Universities Press",
          "SERIES": null,
          "PAGES": "139p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 45,
          "P": "0.0",
          "ISBN": "0-86311-314-1"
        },
        {
          "SLNO": 29,
          "AUTHORS":
              "Padmanabhan (S K), Jindal (B P), Jain (S K), Chatterjee (D N)",
          "TITLE": "Physics",
          "EDITION": 3,
          "YEAR": 1995,
          "PUBLISHER": "CBS Publishers & Distributors",
          "SERIES": null,
          "PAGES": "452p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 70,
          "P": "0.0",
          "ISBN": "81-239-0109-7"
        },
        {
          "SLNO": 30,
          "AUTHORS": "Prakash (Satya)",
          "TITLE": "Circuit Fundamentals and Solid State Electronics",
          "EDITION": 4,
          "YEAR": 1995,
          "PUBLISHER": "Kedar Nath Ram Nath",
          "SERIES": null,
          "PAGES": "399p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 95,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 31,
          "AUTHORS": "Singh (R N)",
          "TITLE": "Electromagnetic Waves and Fields",
          "EDITION": null,
          "YEAR": 1991,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "538p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 54,
          "P": "0.0",
          "ISBN": "0-07-460347-7"
        },
        {
          "SLNO": 32,
          "AUTHORS": "Sidana (H S), Johal (J S)",
          "TITLE": "A Text Book of Numerical Problems in Physics Vol -II",
          "EDITION": 5,
          "YEAR": 1990,
          "PUBLISHER": "Vishal Publications",
          "SERIES": null,
          "PAGES": "266p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 30,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 33,
          "AUTHORS": "Rajaraman (J), Kuriacose (J C)",
          "TITLE": "Thermodynamics for Students of Chemistry",
          "EDITION": 2,
          "YEAR": 1993,
          "PUBLISHER": "Soban Lal Nasin Chand & Co",
          "SERIES": null,
          "PAGES": "518p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 34,
          "AUTHORS": "Gaur (R K), Gupta (S L)",
          "TITLE": "Engineering Physics",
          "EDITION": 7,
          "YEAR": 1995,
          "PUBLISHER": "Dhanpat Rai & Sons",
          "SERIES": null,
          "PAGES": "1020p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 130,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 35,
          "AUTHORS": "Aggarwal (V B)",
          "TITLE": "A Tutorial -Cum Workbook on dBase III +",
          "EDITION": 1,
          "YEAR": 1993,
          "PUBLISHER": "Pitambar Publishing Company",
          "SERIES": null,
          "PAGES": "68p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 16,
          "P": "0.0",
          "ISBN": "81-209-0800-7"
        },
        {
          "SLNO": 36,
          "AUTHORS": "Balasubramanian (K R)",
          "TITLE": "Modern Physics",
          "EDITION": 1,
          "YEAR": 1994,
          "PUBLISHER": "Himalaya Publishing House",
          "SERIES": null,
          "PAGES": "286p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 55,
          "P": "0.0",
          "ISBN": "81-7040-907-1"
        },
        {
          "SLNO": 37,
          "AUTHORS": "Ghosh (N N)",
          "TITLE": "Introductory Physics",
          "EDITION": 5,
          "YEAR": 1993,
          "PUBLISHER": "Bharati Bhavan Publishers & Distributors",
          "SERIES": null,
          "PAGES": "755p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 64,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 38,
          "AUTHORS": "Khanna (D R), Gulati (H R)",
          "TITLE": "Fundamentals of Optics",
          "EDITION": 17,
          "YEAR": 1995,
          "PUBLISHER": "R. Chand & Co., New Delhi",
          "SERIES": null,
          "PAGES": "675p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 95,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 39,
          "AUTHORS": "Mohindroo (K K)",
          "TITLE": "Practical Physics +2",
          "EDITION": 3,
          "YEAR": 1993,
          "PUBLISHER": "Pitambar Publishing Company",
          "SERIES": null,
          "PAGES": "258p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 37,
          "P": "50.0",
          "ISBN": null
        },
        {
          "SLNO": 40,
          "AUTHORS": "Kachhava (C M)",
          "TITLE": "Solid State Physics",
          "EDITION": 3,
          "YEAR": 1994,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "223p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 69,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 41,
          "AUTHORS": "Hariharan (S), Goel (M K)",
          "TITLE": "Physics Objective Type Questions and Answers",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Sterling Publishers",
          "SERIES": null,
          "PAGES": "191p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 40,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 42,
          "AUTHORS": "Murugeshan ",
          "TITLE": "Properies of Matter",
          "EDITION": 1,
          "YEAR": 1995,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "170p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 30,
          "P": "0.0",
          "ISBN": "81-219-0605-9"
        },
        {
          "SLNO": 43,
          "AUTHORS": "Gupta (S L), Kumar (V), Singh (S P)",
          "TITLE": "Electrodynamics",
          "EDITION": 11,
          "YEAR": 1995,
          "PUBLISHER": "Pragati Prakashan",
          "SERIES": null,
          "PAGES": "520p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 90,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 44,
          "AUTHORS": "Duggal (B D), Chhabra (C L), Gupta (P L)",
          "TITLE": "Fundamentals of Modern Physics",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Shoban Lal Nasin Chand",
          "SERIES": null,
          "PAGES": "385p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 50,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 45,
          "AUTHORS": "Chopra (K K), Agrawal (G C)",
          "TITLE": "Electromagnetic Theory Electrodynamics",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Kedar Nath Ram Nath",
          "SERIES": null,
          "PAGES": "494p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 80,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 46,
          "AUTHORS": "Balasubramanian (M R), Krishnamoorthy (S), Murugesan (V)",
          "TITLE": "Engineering Chemistry A Text Book",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Allied Publishers",
          "SERIES": null,
          "PAGES": "487p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 47,
          "AUTHORS": "Sabesan , Dhanalakshmi (A), William (A), Thangaraj (K)",
          "TITLE": "A Text Book of Allied Physics",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Charotar Book Stall",
          "SERIES": null,
          "PAGES": "248p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 40,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 48,
          "AUTHORS": "Narayanan (S), Manicavachagam (Pillay T K)",
          "TITLE": "Differential Equations",
          "EDITION": 9,
          "YEAR": 1994,
          "PUBLISHER": "S. Viswanathan(Print & Pub)",
          "SERIES": null,
          "PAGES": "261p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 25,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 49,
          "AUTHORS": "Kalicharan (Noel)",
          "TITLE": "C by Example",
          "EDITION": null,
          "YEAR": 1996,
          "PUBLISHER": "Cambridge University Press",
          "SERIES": null,
          "PAGES": "362p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 125,
          "P": "0.0",
          "ISBN": "0-521-56700-9"
        },
        {
          "SLNO": 50,
          "AUTHORS": "Stevens (Richard W)",
          "TITLE": "Unix Network Programming",
          "EDITION": null,
          "YEAR": 1996,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "772p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 175,
          "P": "0.0",
          "ISBN": "81-203-0749-6"
        },
        {
          "SLNO": 51,
          "AUTHORS": "Taylor (Oppenshaw E)",
          "TITLE": "Utilisation of Electric Energy ",
          "EDITION": null,
          "YEAR": 1991,
          "PUBLISHER": "Orient Longman",
          "SERIES": null,
          "PAGES": "392p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 145,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 52,
          "AUTHORS": "Gupta (R B), Kishore (Brij)",
          "TITLE": "Electrical Science",
          "EDITION": null,
          "YEAR": 1997,
          "PUBLISHER": "Satya Prakashan",
          "SERIES": null,
          "PAGES": "661p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 70,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 53,
          "AUTHORS": "Spence (Rick)",
          "TITLE": "Clipper Programming Guide ",
          "EDITION": 2,
          "YEAR": 1991,
          "PUBLISHER": "BPB Publications",
          "SERIES": null,
          "PAGES": "610p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 195,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 54,
          "AUTHORS": "Unatkat (Chirag L), Nainani (Hema), Mote (Prakash)",
          "TITLE": "Oracle 6/7 SQL report Writer",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "BPB Publications",
          "SERIES": null,
          "PAGES": "286p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 180,
          "P": "0.0",
          "ISBN": "81-7029-528-9"
        },
        {
          "SLNO": 57,
          "AUTHORS": "Bhattacharya (Pallab)",
          "TITLE": "Semiconductor Optoelectronic Devices",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "535p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 150,
          "P": "0.0",
          "ISBN": "81-203-0878-6"
        },
        {
          "SLNO": 58,
          "AUTHORS": "Partab (H)",
          "TITLE": "Art & Science of Utilisation of Electrical energy",
          "EDITION": 3,
          "YEAR": 1995,
          "PUBLISHER": "Dhanpat Rai & Sons",
          "SERIES": null,
          "PAGES": "699p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 59,
          "AUTHORS": "Sahder (S K), Rana (D S)",
          "TITLE": "Elements of Electrical Science",
          "EDITION": 1,
          "YEAR": 1994,
          "PUBLISHER": "S. Chand & Company, New Delhi",
          "SERIES": null,
          "PAGES": "621p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 125,
          "P": "0.0",
          "ISBN": "81-219-0567-2"
        },
        {
          "SLNO": 60,
          "AUTHORS": "Rai (H M)",
          "TITLE": "Elements of Electronic Instrumentation",
          "EDITION": 4,
          "YEAR": 1995,
          "PUBLISHER": "Satya Prakashan",
          "SERIES": null,
          "PAGES": "585p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 85,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 61,
          "AUTHORS": "Mukhi (H R)",
          "TITLE": "Society Environment and Engineering",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "Satya Prakashan",
          "SERIES": null,
          "PAGES": "596p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 100,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 62,
          "AUTHORS": "Jain (R K)",
          "TITLE": "Machine Design",
          "EDITION": 7,
          "YEAR": 1995,
          "PUBLISHER": "Khanna Publisher",
          "SERIES": null,
          "PAGES": "1558p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 135,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 63,
          "AUTHORS": "Arora (S C), Domkundwar (S), Domkundwar (V)",
          "TITLE": "A Course in Heat and Mass Transfer",
          "EDITION": 4,
          "YEAR": 1995,
          "PUBLISHER": "Dhanpat Rai & Sons",
          "SERIES": null,
          "PAGES": "1614p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 125,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 64,
          "AUTHORS": "Raghavan (V)",
          "TITLE": "Material Science and Engineering A First Course",
          "EDITION": 17,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "400p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": "81-203-0580-9"
        },
        {
          "SLNO": 65,
          "AUTHORS": "Johnson (Curtis)",
          "TITLE": "Process Control Instrumentation Technology",
          "EDITION": 4,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "592p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 195,
          "P": "0.0",
          "ISBN": "81-203-0987-1"
        },
        {
          "SLNO": 66,
          "AUTHORS": "Graham (Neill)",
          "TITLE":
              "Programming and Problem Solving with Pascal introduction to Computer Science",
          "EDITION": 4,
          "YEAR": null,
          "PUBLISHER": "Jaico Publishing House",
          "SERIES": null,
          "PAGES": "519p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 160,
          "P": "0.0",
          "ISBN": "81-7224-044-9"
        },
        {
          "SLNO": 67,
          "AUTHORS": "Bronson (Gary J), Menconi (Stephen J)",
          "TITLE": "A First Book of C Fundamentals of C Programming",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "Jaico Publishing House",
          "SERIES": null,
          "PAGES": "546p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 100,
          "P": "0.0",
          "ISBN": "81-7224-192-5"
        },
        {
          "SLNO": 68,
          "AUTHORS": "Boillot (Michael)",
          "TITLE": "Understanding Forton 77 with Structutral Problem Solving",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Jaico Publishing House",
          "SERIES": null,
          "PAGES": "592p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 110,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 69,
          "AUTHORS": "Mathur (Rajiv)",
          "TITLE": "dBase III Plus for Beginners",
          "EDITION": null,
          "YEAR": 1996,
          "PUBLISHER": "Galgotia Publications",
          "SERIES": null,
          "PAGES": "585p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 136,
          "P": "0.0",
          "ISBN": "81-85623-51-1"
        },
        {
          "SLNO": 70,
          "AUTHORS": "Raghuwanshi (B S)",
          "TITLE":
              "A Course in Workshop Technology Vol -I Manufacturing Processes",
          "EDITION": 8,
          "YEAR": 1994,
          "PUBLISHER": "Dhanpat Rai & Sons",
          "SERIES": null,
          "PAGES": "708p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 71,
          "AUTHORS": "An EFY Enterprices",
          "TITLE": "Electronics Projects Vol -9",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "EFY Enterprises",
          "SERIES": null,
          "PAGES": "197p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 72,
          "AUTHORS": "Deshpande (N D), Deshpande (D A), Ragole (P K)",
          "TITLE": "Coomunication Electronics",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "418p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 99,
          "P": "0.0",
          "ISBN": "0-07-451598-5"
        },
        {
          "SLNO": 73,
          "AUTHORS": "Taub (Herbert), Schilling (Donald L)",
          "TITLE": "Principles of Communication Systems",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "759p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 170,
          "P": "0.0",
          "ISBN": "0-07-451598-5"
        },
        {
          "SLNO": 74,
          "AUTHORS": "Zbar (Paul B), Malvino (Albert P), Miller (Micheal A)",
          "TITLE": "Basic Electronics - A Tex-Lab Manual",
          "EDITION": 7,
          "YEAR": 1995,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "381p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 135,
          "P": "0.0",
          "ISBN": "0-07-462498-9"
        },
        {
          "SLNO": 75,
          "AUTHORS": "Roddy (Dennis), Coolen (John)",
          "TITLE": "Electronic Communications",
          "EDITION": 4,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "820p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 275,
          "P": "0.0",
          "ISBN": "81-203-0984-7"
        },
        {
          "SLNO": 76,
          "AUTHORS": "Amitabah (Ghosh), Asok kumar (Mallik)",
          "TITLE": "Manufacturing Science",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Affiliated East West Press",
          "SERIES": null,
          "PAGES": "434p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 95,
          "P": "0.0",
          "ISBN": "81-85095-85-x"
        },
        {
          "SLNO": 77,
          "AUTHORS": "Singh (Surendra)",
          "TITLE": "Strength of Materials",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Konark Publishers",
          "SERIES": null,
          "PAGES": "724p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 80,
          "P": "0.0",
          "ISBN": "81-220-0058-0"
        },
        {
          "SLNO": 78,
          "AUTHORS": "Bansal (R K)",
          "TITLE": "A Text Book of Strengh of Materials (Mechanics of Solids) ",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Lakshmi Publications",
          "SERIES": null,
          "PAGES": "936p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 150,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 79,
          "AUTHORS": "Mathur (S B)",
          "TITLE": "Mechanical Engineering ;Objective and Conventional Type",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "Dhanpat Rai & Sons",
          "SERIES": null,
          "PAGES": "829p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 65,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 80,
          "AUTHORS": "Tejwani (V K)",
          "TITLE": "Basic Machine Shop Practice Vol -1",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "237p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 69,
          "P": "0.0",
          "ISBN": "0-07-096640-0"
        },
        {
          "SLNO": 81,
          "AUTHORS": "Tejwani (V K)",
          "TITLE": "Basic Machine Shop Practice Vol -2",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "254p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 72,
          "P": "0.0",
          "ISBN": "0-07-451959-x"
        },
        {
          "SLNO": 82,
          "AUTHORS": "Raman ",
          "TITLE": "Principles of Mechanical Measurements",
          "EDITION": null,
          "YEAR": 1992,
          "PUBLISHER": "Oxford & IBH Publishing",
          "SERIES": null,
          "PAGES": "240p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 45,
          "P": "0.0",
          "ISBN": "81-204-0737-7"
        },
        {
          "SLNO": 83,
          "AUTHORS": "Grover (G K)",
          "TITLE": "Mechanical Vibrations",
          "EDITION": 5,
          "YEAR": 1993,
          "PUBLISHER": "Nem Chand & Bros",
          "SERIES": null,
          "PAGES": "534p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 90,
          "P": "0.0",
          "ISBN": "81-85240-55-8"
        },
        {
          "SLNO": 84,
          "AUTHORS": "Punmia (B C), Bansi Lal (Pandi Brij)",
          "TITLE": "Irrigation and Water Power Engineering",
          "EDITION": 12,
          "YEAR": 1995,
          "PUBLISHER": "Lakshmi Publications",
          "SERIES": null,
          "PAGES": "985p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 125,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 85,
          "AUTHORS": "Venugopal (K R) Vimala (H S)",
          "TITLE": "Programming with Fortran",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "693p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 90,
          "P": "0.0",
          "ISBN": "0-07-462486-5"
        },
        {
          "SLNO": 86,
          "AUTHORS": "Koparkar (Pramod)",
          "TITLE": "Pascal for You",
          "EDITION": null,
          "YEAR": 1994,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "262p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": "0-07-462205-6"
        },
        {
          "SLNO": 87,
          "AUTHORS": "Gupta (Sanjeeva), Arora (Dimesh), Sarma (Satya Bhushan)",
          "TITLE": "Microwave Engineering",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Khanna Publisher",
          "SERIES": null,
          "PAGES": "268p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 35,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 89,
          "AUTHORS": "Anand (D K), Zmood (R B)",
          "TITLE": "Introduction to Control Systems",
          "EDITION": 3,
          "YEAR": 1995,
          "PUBLISHER": "Asian Books",
          "SERIES": null,
          "PAGES": "730p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 285,
          "P": "0.0",
          "ISBN": "81-86299-02-5"
        },
        {
          "SLNO": 90,
          "AUTHORS": "Rao (S S)",
          "TITLE": "Optimization Theory and Applications",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "New Age International",
          "SERIES": null,
          "PAGES": "747p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 175,
          "P": "0.0",
          "ISBN": "0-85226-756-8"
        },
        {
          "SLNO": 91,
          "AUTHORS": "Nagrath (I J), Gopal (M)",
          "TITLE": "Control Systems Engineering",
          "EDITION": 2,
          "YEAR": 1995,
          "PUBLISHER": "New Age International",
          "SERIES": null,
          "PAGES": "725p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 160,
          "P": "0.0",
          "ISBN": "0-85226-605-7"
        },
        {
          "SLNO": 92,
          "AUTHORS": "Heitner (Joseph)",
          "TITLE": "Automotive Mechanics  Principles and Practice",
          "EDITION": null,
          "YEAR": 1967,
          "PUBLISHER": "Affiliated East West Press",
          "SERIES": null,
          "PAGES": "608p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 80,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 93,
          "AUTHORS": "Hillier (Frederick S)",
          "TITLE": "Operations Research",
          "EDITION": 2,
          "YEAR": 1994,
          "PUBLISHER": "CBS Publishers & Distributors",
          "SERIES": null,
          "PAGES": "800p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 130,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 94,
          "AUTHORS": "Venk (Ernest), Billiet (Wdler)",
          "TITLE": "Automotive Engines maintenance and repair",
          "EDITION": null,
          "YEAR": 1992,
          "PUBLISHER": "D. B. Taraporevala sons & Co",
          "SERIES": null,
          "PAGES": "480p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 299,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 95,
          "AUTHORS": "Crouse (William H), Anglin (Donald L)",
          "TITLE": "Automotive Mechanics",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Tata McGraw Hill, New Delhi",
          "SERIES": null,
          "PAGES": "665p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 210,
          "P": "0.0",
          "ISBN": "0-07-099215-0"
        },
        {
          "SLNO": 96,
          "AUTHORS": "Venk (Ernest), Billiet (Wdler)",
          "TITLE": "Automotive Maintenance and Trouble Shooting",
          "EDITION": null,
          "YEAR": 1990,
          "PUBLISHER": "D. B. Taraporevala sons & Co",
          "SERIES": null,
          "PAGES": "426p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 299,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 97,
          "AUTHORS": "Rai (H M)",
          "TITLE": "A Textbook on Control System Engineering",
          "EDITION": 3,
          "YEAR": 1995,
          "PUBLISHER": "Satya Prakashan",
          "SERIES": null,
          "PAGES": "729p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 85,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 98,
          "AUTHORS": "Palani (S)",
          "TITLE": "Control Systems ",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Shanmuga Priya Publishers",
          "SERIES": null,
          "PAGES": "575p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 110,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 99,
          "AUTHORS": "Manke (B S)",
          "TITLE": "Linear Control Systems",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Khanna Publisher",
          "SERIES": null,
          "PAGES": "496p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 60,
          "P": "0.0",
          "ISBN": null
        },
        {
          "SLNO": 100,
          "AUTHORS": "Ermine (Jean Louis)",
          "TITLE": "Expert sytems Theory and Practice",
          "EDITION": null,
          "YEAR": 1995,
          "PUBLISHER": "Prentice Hall of India, New Delhi",
          "SERIES": null,
          "PAGES": "180p",
          "PRICE_FOREIGN": null,
          "PRICE_INR": 75,
          "P": "0.0",
          "ISBN": "81-203-0919-7"
        }
      ];
      final List<Location> l = <Location>[];
      for (final dynamic data in list) {
        final Map<String, dynamic> d = data as Map<String, dynamic>;
        l.add(Location.fromJson(d));
      }
      return l.toBuiltList();
    }
  }

  fetchAlbum() async {
    final response =
        await http.get(Uri.parse('http://mark.bslmeiyu.com/api/getplaces'));

    try {
      if (response.statusCode == 200) {
        List<dynamic> list = json.decode(response.body);
        // print(list);
        return list.map((e) => DataModel.fromJson(e)).toList();
      } else {
        return <DataModel>[];
      }
    } catch (e) {
      print(e);
      return <DataModel>[];
    }
  }
}

class DataModel {
  String name;
  String img;
  int price;
  int people;
  int stars;
  String description;
  String location;
  DataModel({
    required this.name,
    required this.img,
    required this.price,
    required this.people,
    required this.stars,
    required this.description,
    required this.location,
  });
  factory DataModel.fromJson(Map<String, dynamic> json) {
    return DataModel(
        name: json["name"],
        img: json["img"],
        price: json["price"],
        people: json["people"],
        stars: json["stars"],
        description: json["description"],
        location: json["location"]);
  }
}
